interface countryMap {
    [name: string]: string
}

export const countryCode: countryMap = {
    "united states" : "US",
    "usa" : "US",
    "united states of america" : "US",
    "andorra" : "AD",
    "united arab emirates" : "AE",
    "UAE" : "AE",
    "afghanistan" : "AF",
    "antigua and barbuda" : "AG",
    "anguilla" : "AI",
    "albania" : "AL",
    "armenia" : "AM",
    "angola" : "AO",
    "antarctica" : "AQ",
    "argentina" : "AR",
    "american samoa" : "AS",
    "austria" : "AT",
    "australia" : "AU",
    "aruba" : "AW",
    "åland islands" : "AX",
    "azerbaijan" : "AZ",
    "bosnia and herzegovina" : "BA",
    "barbados" : "BB",
    "bangladesh" : "BD",
    "belgium" : "BE",
    "burkina faso" : "BF",
    "bulgaria" : "BG",
    "bahrain" : "BH",
    "burundi" : "BI",
    "benin" : "BJ",
    "saint bathélemy" : "BL",
    "brunei" :"BN",
    "bolivia" : "BO",
    "bonaire" : "BQ",
    "brazil" : "BR",
    "bahamas" : "BS",
    "bhutan" : "BT",
    "belarus" : "BY",
    "belize" : "BY",
    "canada" : "CA",
    "cocoa islands" : "CC",
    "democratic republic of congo" : "CD",
    "central african republic" : "CD",
    "congo" : "CG",
    "switzerland" : "CH",
    "cote d'ivoire" : "CI",
    "cook islands" : "CK",
    "chile" : "CL",
    "colombia" : "CO",
    "costa rica" : "CR",
    "cuba" : "CU",
    "cabo verde" : "CV",
    "curacao" : "CW",
    "christmas island" : "CX",
    "cyprus" : "CY",
    "czech republic" : "CZ",
    "germany" : "DE",
    "djibouti" : "DJ",
    "denmark" : "DK",
    "dominican republic" : "DO",
    "algeria" : "DZ",
    "ecuador" : "EC",
    "estonia" : "EE",
    "eqypt" : "EG",
    "western sahara" : "EH",
    "eritrea" : "ER",
    "spain"	:	"ES"	,
    "ethiopia" : "ET"	,
    "finland" :	"FI"	,
    "fiji"	:	"FJ"	,
    "falkland islands"	:	"FK"	,
    "micronesia"	:	"FM"	,
    "faroe islands"	:	"FO"	,
    "france"	:	"FR"	,
    "gabon"	:	"GA"	,
    "united kingdom"	:	"GB"	,
    "grenada"	:	"GD"	,
    "georgia"	:	"GE"	,
    "french guiana"	:	"GF"	,
    "guernsey"	:	"GG"	,
    "ghana"	:	"GH"	,
    "gibraltar"	:	"GI"	,
    "greenland"	:	"GL"	,
    "gambia"	:	"GM"	,
    "guinea"	:	"GN"	,
    "guadeloupe"	:	"GP"	,
    "equatorial guinea"	:	"GQ"	,
    "greece"	:	"GR"	,
    "south georgia and the south sandwich islands"	:	"GS"	,
    "guatemala"	:	"GT"	,
    "guam"	:	"GU"	,
    "guinea-bissau"	:	"GW"	,
    "guyana"	:	"GY"	,
    "hong kong"	:	"HK"	,
    "heard island and mcdonald islands"	:	"HM"	,
    "honduras"	:	"HN"	,
    "croatia"	:	"HR"	,
    "haiti"	:	"HT"	,
    "hungary"	:	"HU"	,
    "indonesia"	:	"ID"	,
    "ireland"	:	"IE"	,
    "israel"	:	"IL"	,
    "isle of man"	:	"IM"	,
    "india"	:	"IN"	,
    "british indian ocean territory"	:	"IO"	,
    "iraq"	:	"IQ"	,
    "iran"	:	"IR"	,
    "iceland"	:	"IS"	,
    "italy"	:	"IT"	,
    "jersey"	:	"JE"	,
    "jamaica"	:	"JM"	,
    "jordan"	:	"JO"	,
    "japan"	:	"JP"	,
    "kenya"	:	"KE"	,
    "kyrgyzstan"	:	"KG"	,
    "cambodia"	:	"KH"	,
    "kiribati"	:	"KI"	,
    "comoros"	:	"KM"	,
    "saint kitts and nevis"	:	"KN"	,
    "north korea"	:	"KP"	,
    "south korea"	:	"KR"	,
    "kuwait"	:	"KW"	,
    "cayman islands"	:	"KY"	,
    "kazakhstan"	:	"KZ"	,
    "lao people's democratic republic"	:	"LA"	,
    "lebanon"	:	"LB"	,
    "saint lucia"	:	"LC"	,
    "liechtenstein"	:	"LI"	,
    "sri lanka"	:	"LK"	,
    "liberia"	:	"LR"	,
    "lesotho"	:	"LS"	,
    "lithuania"	:	"LT"	,
    "luxembourg"	:	"LU"	,
    "latvia"	:	"LV"	,
    "libya"	:	"LY"	,
    "morocco"	:	"MA"	,
    "monaco"	:	"MC"	,
    "moldova, republic of"	:	"MD"	,
    "montenegro"	:	"ME"	,
    "saint martin"	:	"MF"	,
    "madagascar"	:	"MG"	,
    "marshall islands"	:	"MH"	,
    "north macedonia"	:	"MK"	,
    "mali"	:	"ML"	,
    "myanmar"	:	"MM"	,
    "mongolia"	:	"MN"	,
    "macao"	:	"MO"	,
    "northern mariana islands"	:	"MP"	,
    "martinique"	:	"MQ"	,
    "mauritania"	:	"MR"	,
    "montserrat"	:	"MS"	,
    "malta"	:	"MT"	,
    "mauritius"	:	"MU"	,
    "maldives"	:	"MV"	,
    "malawi"	:	"MW"	,
    "mexico"	:	"MX"	,
    "malaysia"	:	"MY"	,
    "mozambique"	:	"MZ"	,
    "namibia"	:	"NA"	,
    "new caledonia"	:	"NC"	,
    "niger"	:	"NE"	,
    "norfolk island"	:	"NF"	,
    "nigeria"	:	"NG"	,
    "nicaragua"	:	"NI"	,
    "netherlands"	:	"NL"	,
    "norway"	:	"NO"	,
    "nepal"	:	"NP"	,
    "nauru"	:	"NR"	,
    "niue"	:	"NU"	,
    "new zealand"	:	"NZ"	,
    "oman"	:	"OM"	,
    "panama"	:	"PA"	,
    "peru"	:	"PE"	,
    "french polynesia"	:	"PF"	,
    "papua new guinea"	:	"PG"	,
    "philippines"	:	"PH"	,
    "pakistan"	:	"PK"	,
    "poland"	:	"PL"	,
    "saint pierre and miquelon"	:	"PM"	,
    "pitcairn"	:	"PN"	,
    "puerto rico"	:	"PR"	,
    "palestine"	:	"PS"	,
    "portugal"	:	"PT"	,
    "palau"	:	"PW"	,
    "paraguay"	:	"PY"	,
    "qatar"	:	"QA"	,
    "réunion"	:	"RE"	,
    "romania"	:	"RO"	,
    "serbia"	:	"RS"	,
    "russia"	:	"RU"	,
    "rwanda"	:	"RW"	,
    "saudi arabia"	:	"SA"	,
    "solomon islands"	:	"SB"	,
    "seychelles"	:	"SC"	,
    "sudan"	:	"SD"	,
    "sweden"	:	"SE"	,
    "singapore"	:	"SG"	,
    "saint helena"	:	"SH"	,
    "slovenia"	:	"SI"	,
    "svalbard and jan mayen"	:	"SJ"	,
    "slovakia"	:	"SK"	,
    "sierra leone"	:	"SL"	,
    "san marino"	:	"SM"	,
    "senegal"	:	"SN"	,
    "somalia"	:	"SO"	,
    "suriname"	:	"SR"	,
    "south sudan"	:	"SS"	,
    "sao tome and principe"	:	"ST"	,
    "el salvador"	:	"SV"	,
    "sint maarten"	:	"SX"	,
    "syria"	:	"SY"	,
    "eswatini"	:	"SZ"	,
    "turks and caicos islands"	:	"TC"	,
    "chad"	:	"TD"	,
    "french southern territories"	:	"TF"	,
    "togo"	:	"TG"	,
    "thailand"	:	"TH"	,
    "tajikistan"	:	"TJ"	,
    "tokelau"	:	"TK"	,
    "timor-leste"	:	"TL"	,
    "turkmenistan"	:	"TM"	,
    "tunisia"	:	"TN"	,
    "tonga"	:	"TO"	,
    "turkey"	:	"TR"	,
    "trinidad and tobago"	:	"TT"	,
    "tuvalu"	:	"TV"	,
    "taiwan"	:	"TW"	,
    "tanzania, united republic of"	:	"TZ"	,
    "ukraine"	:	"UA"	,
    "uganda"	:	"UG"	,
    "united states minor outlying islands"	:	"UM"	,
    "uruguay"	:	"UY"	,
    "uzbekistan"	:	"UZ"	,
    "holy see"	:	"VA"	,
    "saint vincent and the grenadines"	:	"VC"	,
    "venezuela"	:	"VE"	,
    "british virgin islands"	:	"VG"	,
    "virgin islands (u.s.)"	:	"VI"	,
    "viet nam"	:	"VN"	,
    "vanuatu"	:	"VU"	,
    "wallis and futuna"	:	"WF"	,
    "samoa"	:	"WS"	,
    "yemen"	:	"YE"	,
    "mayotte"	:	"YT"	,
    "south africa"	:	"ZA"	,
    "zambia"	:	"ZM"	,
    "zimbabwe"	:	"ZW"	
}


    

    
   


 